# Конкретні припущення (оновлюй під актуальні умови):
xp:
  base_quests:
    # фіксовані квести першої хвилі
    - { name: "Profile setup", xp: 120 }
    - { name: "First listing", xp: 300 }
    - { name: "First purchase", xp: 450 }
  repeatables:
    # повторювані дії (припущення!)
    swap_per_tx:
      xp_per_tx: 35         # XP за 1 свап
      max_per_day: 20
    volume_bonus:
      # XP за обсяг (кумулятивно за день)
      tiers:
        - { min_usd: 0,    xp: 0 }
        - { min_usd: 10,   xp: 15 }
        - { min_usd: 50,   xp: 120 }
        - { min_usd: 100,  xp: 300 }
fees:
  l2_gas_per_tx_usd: 0.04   # середня вартість газу L2 за 1 операцію
  dex_fee_pct: 0.003        # 0.3% DEX fee
  price_impact_pct: 0.001   # 0.1% ковзання
levels:
  # орієнтовні пороги XP для рівнів сундука
  - { level: 1,  xp: 0 }
  - { level: 2,  xp: 400 }
  - { level: 3,  xp: 900 }
  - { level: 4,  xp: 1500 }
  - { level: 5,  xp: 2300 }
  - { level: 6,  xp: 3300 }
  - { level: 7,  xp: 4600 }
  - { level: 8,  xp: 6200 }
  - { level: 9,  xp: 8200 }
  - { level: 10, xp: 10700 }
usd_ref:
  default_budget_usd: 50
